<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>GitHub_KPI_tool_Infrastructure</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.1.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.2" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.3" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Npgsql" Version="9.0.3" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
      <PackageReference Include="Octokit" Version="14.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GitHub-KPI-tool-Application\GitHub-KPI-tool-Application.csproj" />
    </ItemGroup>

</Project>
